import type { OrdemServico, Cliente } from './types'

export const ATENDENTES = [
  'Carlos Silva',
  'Roberto Almeida',
  'Fernando Costa',
]

export const CLIENTES_MOCK: Cliente[] = [
  {
    id: '1',
    nome: 'Joao Pedro Mendes',
    cpf: '123.456.789-00',
    telefone: '(11) 99999-0001',
    apelido: 'JP',
    instagram: '@jpmendes',
    endereco: 'Rua das Flores, 123',
    nascimento: '1990-05-15',
    autoriza_instagram: true,
    autoriza_lembretes: true,
  },
  {
    id: '2',
    nome: 'Maria Fernanda Silva',
    cpf: '987.654.321-00',
    telefone: '(11) 98888-0002',
    apelido: 'Mafe',
    instagram: '@mafe_rider',
    endereco: 'Av. Paulista, 1000',
    nascimento: '1985-11-20',
    autoriza_instagram: false,
    autoriza_lembretes: true,
  },
  {
    id: '3',
    nome: 'Lucas Oliveira',
    cpf: '456.789.123-00',
    telefone: '(11) 97777-0003',
    apelido: '',
    instagram: '',
    endereco: 'Rua Augusta, 500',
    nascimento: '1995-03-10',
    autoriza_instagram: true,
    autoriza_lembretes: false,
  },
]

export const ORDENS_MOCK: OrdemServico[] = [
  {
    id: 'os-001',
    numero: 1024,
    cliente: CLIENTES_MOCK[0],
    motos: [
      { id: 'm1', modelo: 'Honda CB 500F', ano: '2022', cor: 'Preta', placa: 'ABC1D23', km: '15000' },
    ],
    data_entrada: '2026-03-01',
    quem_retira: 'cliente',
    atendente: 'Carlos Silva',
    adesivo_loja: true,
    descricao_servico: 'Troca de oleo e filtro. Revisar corrente e ajustar embreagem.',
    status: 'em_andamento',
    checklist: [
      { id: 'c1', label: 'Oleo trocado', checked: true },
      { id: 'c2', label: 'Filtro substituido', checked: true },
      { id: 'c3', label: 'Corrente ajustada', checked: false },
      { id: 'c4', label: 'Embreagem regulada', checked: false },
    ],
    materiais: [
      { id: 'mt1', nome: 'Oleo Motor 10W40', quantidade: 3, valor: 45.00 },
      { id: 'mt2', nome: 'Filtro de Oleo', quantidade: 1, valor: 32.00 },
    ],
    pagamentos: [],
    created_at: '2026-03-01T10:00:00',
    updated_at: '2026-03-03T14:30:00',
  },
  {
    id: 'os-002',
    numero: 1025,
    cliente: CLIENTES_MOCK[1],
    motos: [
      { id: 'm2', modelo: 'Yamaha MT-07', ano: '2023', cor: 'Azul', placa: 'XYZ9A87', km: '8500' },
    ],
    data_entrada: '2026-03-02',
    quem_retira: 'outro',
    retirada_nome: 'Pedro Silva',
    retirada_telefone: '(11) 96666-0010',
    retirada_cpf: '111.222.333-44',
    atendente: 'Roberto Almeida',
    adesivo_loja: false,
    descricao_servico: 'Revisao completa 10.000km. Trocar pastilhas de freio dianteira.',
    status: 'aguardando_peca',
    checklist: [
      { id: 'c5', label: 'Revisao geral feita', checked: true },
      { id: 'c6', label: 'Pastilhas trocadas', checked: false },
      { id: 'c7', label: 'Fluido de freio verificado', checked: true },
    ],
    materiais: [
      { id: 'mt3', nome: 'Pastilha Freio Dianteira', quantidade: 1, valor: 120.00 },
    ],
    pagamentos: [
      { id: 'pg1', metodo: 'pix', valor: 200.00, data: '2026-03-02' },
    ],
    created_at: '2026-03-02T09:00:00',
    updated_at: '2026-03-04T11:00:00',
  },
  {
    id: 'os-003',
    numero: 1026,
    cliente: CLIENTES_MOCK[2],
    motos: [
      { id: 'm3', modelo: 'Kawasaki Z400', ano: '2024', cor: 'Verde', placa: 'KWS4E56', km: '3200' },
      { id: 'm4', modelo: 'Honda CG 160', ano: '2021', cor: 'Vermelha', placa: 'CG16F78', km: '25000' },
    ],
    data_entrada: '2026-03-03',
    quem_retira: 'cliente',
    atendente: 'Fernando Costa',
    adesivo_loja: true,
    descricao_servico: 'Instalacao de slider e protetor de motor na Z400. CG: troca de pneu traseiro.',
    status: 'aberta',
    checklist: [
      { id: 'c8', label: 'Slider instalado', checked: false },
      { id: 'c9', label: 'Protetor instalado', checked: false },
      { id: 'c10', label: 'Pneu traseiro CG trocado', checked: false },
    ],
    materiais: [
      { id: 'mt4', nome: 'Slider Procton Z400', quantidade: 1, valor: 280.00 },
      { id: 'mt5', nome: 'Protetor Motor Z400', quantidade: 1, valor: 350.00 },
      { id: 'mt6', nome: 'Pneu Tras. CG 160', quantidade: 1, valor: 180.00 },
    ],
    pagamentos: [],
    created_at: '2026-03-03T08:30:00',
    updated_at: '2026-03-03T08:30:00',
  },
  {
    id: 'os-004',
    numero: 1027,
    cliente: CLIENTES_MOCK[0],
    motos: [
      { id: 'm5', modelo: 'Honda CB 500F', ano: '2022', cor: 'Preta', placa: 'ABC1D23', km: '15200' },
    ],
    data_entrada: '2026-02-15',
    quem_retira: 'cliente',
    atendente: 'Carlos Silva',
    adesivo_loja: true,
    descricao_servico: 'Troca de pneus dianteiro e traseiro.',
    status: 'entregue',
    checklist: [
      { id: 'c11', label: 'Pneu dianteiro trocado', checked: true },
      { id: 'c12', label: 'Pneu traseiro trocado', checked: true },
      { id: 'c13', label: 'Balanceamento feito', checked: true },
    ],
    materiais: [
      { id: 'mt7', nome: 'Pneu Dianteiro Michelin', quantidade: 1, valor: 420.00 },
      { id: 'mt8', nome: 'Pneu Traseiro Michelin', quantidade: 1, valor: 520.00 },
    ],
    pagamentos: [
      { id: 'pg2', metodo: 'cartao_credito', valor: 940.00, data: '2026-02-20' },
    ],
    created_at: '2026-02-15T11:00:00',
    updated_at: '2026-02-20T16:00:00',
  },
  {
    id: 'os-005',
    numero: 1028,
    cliente: CLIENTES_MOCK[1],
    motos: [
      { id: 'm6', modelo: 'Yamaha MT-07', ano: '2023', cor: 'Azul', placa: 'XYZ9A87', km: '8700' },
    ],
    data_entrada: '2026-02-28',
    quem_retira: 'cliente',
    atendente: 'Roberto Almeida',
    adesivo_loja: true,
    descricao_servico: 'Troca de oleo sintetico e revisao de suspensao.',
    status: 'finalizada',
    checklist: [
      { id: 'c14', label: 'Oleo trocado', checked: true },
      { id: 'c15', label: 'Suspensao revisada', checked: true },
    ],
    materiais: [
      { id: 'mt9', nome: 'Oleo Sintetico 10W50', quantidade: 4, valor: 55.00 },
    ],
    pagamentos: [
      { id: 'pg3', metodo: 'dinheiro', valor: 320.00, data: '2026-03-01' },
    ],
    created_at: '2026-02-28T14:00:00',
    updated_at: '2026-03-01T10:00:00',
  },
]
