project_id = "cdigibzeweugjysiyicw"

[functions.enviar-documento-whatsapp]
verify_jwt = false

[functions.check-maintenance-reminders]
verify_jwt = false

[functions.send-satisfaction-survey]
verify_jwt = false

[functions.satisfaction-public]
verify_jwt = false