ALTER TABLE store_settings
  ADD COLUMN IF NOT EXISTS store_phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS store_address TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS store_cnpj TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS store_instagram TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS store_owner TEXT NOT NULL DEFAULT '';
