// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Captura o hash E search ANTES do SDK processar e limpar o token de invite/recovery
export const INITIAL_URL_HASH = typeof window !== 'undefined' ? window.location.hash : '';
export const INITIAL_URL_SEARCH = typeof window !== 'undefined' ? window.location.search : '';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Criar fallback de storage para Safari Private Browsing
const createSafariCompatibleStorage = () => {
  console.log('🔐 Criando storage compatível com Safari...');
  const inMemoryStorage: Record<string, string> = {};
  
  // Usar sempre in-memory storage para evitar problemas de segurança em Safari
  const storage = {
    getItem: (key: string) => {
      const value = inMemoryStorage[key] || null;
      console.log('📦 Storage.getItem:', key, '=', value ? 'found' : 'null');
      return value;
    },
    setItem: (key: string, value: string) => {
      console.log('📦 Storage.setItem:', key);
      inMemoryStorage[key] = value;
    },
    removeItem: (key: string) => {
      console.log('📦 Storage.removeItem:', key);
      delete inMemoryStorage[key];
    },
    clear: () => {
      console.log('📦 Storage.clear');
      Object.keys(inMemoryStorage).forEach(key => {
        delete inMemoryStorage[key];
      });
    },
    key: (index: number) => {
      const keys = Object.keys(inMemoryStorage);
      return keys[index] || null;
    },
    get length() {
      return Object.keys(inMemoryStorage).length;
    }
  };
  
  console.log('✅ Storage criado com sucesso');
  return storage;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createSafariCompatibleStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  },
});